[package]
name = "statix"
version = "0.5.8"
edition = "2018"
license = "MIT"
authors = [ "Akshay <nerdy@peppe.rs>" ]
description = "Lints and suggestions for the Nix programming language"

[lib]
name = "statix"
path = "src/lib.rs"

[[bin]]
name = "statix"
path = "src/main.rs"

[dependencies]
ariadne = "0.5.0"
clap = { version = "4.5.26", features = [ "derive" ] }
ignore = "0.4.18"
lib = { path = "../lib" }
rayon = "1.5.1"
rnix = "0.12"
similar = "2.1.0"
thiserror = "2.0.11"
toml = "0.8.19"
vfs = { path = "../vfs" }
serde = { version = "1.0.68", features = [ "derive" ] }
serde_json = { version = "1.0.68", optional = true }

[dev-dependencies]
insta = "1.8.0"
strip-ansi-escapes = "0.2.0"

[features]
json = [ "lib/json-out", "serde_json" ]
